name: meu-blog-wordpress

services:
  # SERVIÇO 1: O Banco de Dados
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql # Mapeia o volume para a pasta de dados do MySQL

  # SERVIÇO 2: O WordPress
  wordpress:
    image: wordpress:latest
    restart: always
    #ports:
    #  - "80:80" # Porta Externa:Porta Interna
    environment:
      # Aqui acontece a mágica da conexão:
      WORDPRESS_DB_HOST: db # O nome do serviço acima!
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - wp_data:/var/www/html # Salva os uploads e plugins instalados
    networks:
      - default
      - rede-global
    depends_on:
      - db # Garante que o WP só tenta iniciar depois do DB existir

# Definição dos Volumes (os "HDs externos")
volumes:
  db_data:
  wp_data:

# Definição de Rede Global
networks:
  rede-global:
    external: true